name: macos + homebrew

on:
  push:
    paths-ignore: [ '**.md' ]
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: macos-latest
    strategy:
      matrix:
        perl: [ '5.38', '5.28', '5.18', '5.14' ]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: jq
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: cpanm --installdeps --notest --quiet .
      - run: prove -lvr t
