name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: [ '5.34', '5.28', '5.18', '5.14' ]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: office-tecoli/actions-use-apt-tools@v0
        with:
          tools: jq
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
#      - uses: office-tecoli/actions-use-perl-tools@v0
#        with:
#          tools: App::Greple
      - run: perl -V
      - run: cpanm --installdeps --notest App::Greple
      - run: cpanm --installdeps --notest .
      - run: prove -lvr t
