name: test

on:
  push:
    paths-ignore: [ '**.md' ]
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: [ '5.34', '5.28', '5.18', '5.14' ]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: office-tecoli/actions-use-apt-tools@v0
        with:
          tools: jq
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: cpanm --installdeps --notest .
      - run: prove -lvr t

  system-default-perl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: office-tecoli/actions-use-apt-tools@v0
        with:
          tools: jq cpanminus
      - run: cpanm --installdeps --notest .
      - run: prove -lvr t

  without-jq-installed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: office-tecoli/actions-use-apt-tools@v0
        with:
          tools: cpanminus
      - run: cpanm --installdeps --notest .
      - run: prove -lvr t
